params ["_container", "_caller", "_actionId"];
[_container, ["Purchase AK-15: $350", "Economy System\functions\FN_PurchaseItem.sqf", ["arifle_AK12_F",350],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase AKM: $175", "Economy System\functions\FN_PurchaseItem.sqf", ["arifle_AKM_F",175],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase AKS-74U: $80", "Economy System\functions\FN_PurchaseItem.sqf", ["arifle_AKS_F",80],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase ASP-1 KIR: $750", "Economy System\functions\FN_PurchaseItem.sqf", ["srifle_DMR_04_F",750],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase CPW: $45", "Economy System\functions\FN_PurchaseItem.sqf", ["hgun_PDW2000_F",45],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase CTAR-21: $175", "Economy System\functions\FN_PurchaseItem.sqf", ["arifle_TRG20_F",175],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase CYRUS: $1,250", "Economy System\functions\FN_PurchaseItem.sqf", ["Rusty_DMR_05_base_F",1250],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase F2000: $275", "Economy System\functions\FN_PurchaseItem.sqf", ["arifle_Mk20_F",275],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase F2000 TACTICAL: $250", "Economy System\functions\FN_PurchaseItem.sqf", ["arifle_Mk20C_F",250],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase FN MINIMI SPW: $500", "Economy System\functions\FN_PurchaseItem.sqf", ["LMG_03_F",500],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase GM6 LYNX: $1,750", "Economy System\functions\FN_PurchaseItem.sqf", ["srifle_GM6_F",1750],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase HK121: $1,500", "Economy System\functions\FN_PurchaseItem.sqf", ["MMG_01_tan_F",1500],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase HK416A5 11IN: $285", "Economy System\functions\FN_PurchaseItem.sqf", ["arifle_SPAR_01_blk_F",285],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase HK416A5 14.5IN: $300", "Economy System\functions\FN_PurchaseItem.sqf", ["arifle_SPAR_02_blk_F",300],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase HK417A5 20IN: $500", "Economy System\functions\FN_PurchaseItem.sqf", ["arifle_SPAR_03_blk_F",500],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase KH2002 SAMA: $400", "Economy System\functions\FN_PurchaseItem.sqf", ["arifle_Katiba_F",400],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase KH2002C SAMA: $380", "Economy System\functions\FN_PurchaseItem.sqf", ["arifle_Katiba_C_F",380],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase KOZLICE 12G: $30", "Economy System\functions\FN_PurchaseItem.sqf", ["sgun_HunterShotgun_01_F",30],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase LWMMG: $1,500", "Economy System\functions\FN_PurchaseItem.sqf", ["MMG_02_black_F",1500],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase M14: $350", "Economy System\functions\FN_PurchaseItem.sqf", ["srifle_DMR_06_hunter_F",350],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase M14 DMR: $650", "Economy System\functions\FN_PurchaseItem.sqf", ["srifle_DMR_06_camo_F",650],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase M200 INTERVENTION: $1,600", "Economy System\functions\FN_PurchaseItem.sqf", ["srifle_LRR_camo_F",1600],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase MAR 10: $1,000", "Economy System\functions\FN_PurchaseItem.sqf", ["Rusty_srifle_DMR_02_F",1000],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase MK-I EMR: $450", "Economy System\functions\FN_PurchaseItem.sqf", ["Rusty_srifle_DMR_03_F",450],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase MP5K: $75", "Economy System\functions\FN_PurchaseItem.sqf", ["SMG_05_F",75],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase MSBS GROT: $400", "Economy System\functions\FN_PurchaseItem.sqf", ["arifle_MSBS65_black_F",400],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase MSBS GROT MR: $500", "Economy System\functions\FN_PurchaseItem.sqf", ["arifle_MSBS65_Mark_F",500],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase MSBSGROT SG: $500", "Economy System\functions\FN_PurchaseItem.sqf", ["arifle_MSBS65_UBS_F",500],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase MX: $400", "Economy System\functions\FN_PurchaseItem.sqf", ["arifle_MX_Black_F",400],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase MX LSW: $500", "Economy System\functions\FN_PurchaseItem.sqf", ["arifle_MX_SW_Black_F",500],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase MXC: $325", "Economy System\functions\FN_PurchaseItem.sqf", ["arifle_MXC_Black_F",325],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase MXM: $450", "Economy System\functions\FN_PurchaseItem.sqf", ["arifle_MXM_Black_F",450],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase NAVID 9.3: $1,750", "Economy System\functions\FN_PurchaseItem.sqf", ["Rusty_MMG_01_tan_F",1750],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase NOREEN ULR: $800", "Economy System\functions\FN_PurchaseItem.sqf", ["srifle_DMR_02_camo_F",800],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase P90: $60", "Economy System\functions\FN_PurchaseItem.sqf", ["SMG_03C_black",60],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase PS90: $70", "Economy System\functions\FN_PurchaseItem.sqf", ["SMG_03_black",70],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase QBU-88: $425", "Economy System\functions\FN_PurchaseItem.sqf", ["srifle_DMR_07_blk_F",425],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase QBZ-95-1: $350", "Economy System\functions\FN_PurchaseItem.sqf", ["arifle_CTAR_blk_F",350],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase RFB SDAR: $200", "Economy System\functions\FN_PurchaseItem.sqf", ["arifle_SDAR_F",200],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase RPK: $500", "Economy System\functions\FN_PurchaseItem.sqf", ["arifle_RPK12_F",500],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase SIG 556: $400", "Economy System\functions\FN_PurchaseItem.sqf", ["srifle_DMR_03_woodland_F",400],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase STONER 99 LMG: $600", "Economy System\functions\FN_PurchaseItem.sqf", ["LMG_Mk200_F",600],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase TAR-21: $300", "Economy System\functions\FN_PurchaseItem.sqf", ["arifle_TRG21_F",300],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase VECTOR SMG: $50", "Economy System\functions\FN_PurchaseItem.sqf", ["SMG_01_F",50],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase VS-121: $350", "Economy System\functions\FN_PurchaseItem.sqf", ["srifle_DMR_01_F",350],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase XTS: $1,500", "Economy System\functions\FN_PurchaseItem.sqf", ["DSA_XTS",500],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];
[_container, ["Purchase ZAFIR: $500", "Economy System\functions\FN_PurchaseItem.sqf", ["Rusty_LMG_Zafir_F",500],1.5,true,false,"","true",3]] remoteExec ['addAction', 0, _container];